version: '3.8'

services:
  core-engine:
    build: ./services/core-engine
    ports:
      - 8080:8080
    networks:
      - docker-networks
    environment:
      - DATABASE_MASTER_HOST=postgres
      - DATABASE_SLAVE_HOST=postgres
      - REDIS_ADDRESS=redis:6379
      - KAFKA_ADDRESS=kafka:9092

  matching-engine:
    build: ./services/matching-engine
    ports:
      - 8083:8083
    networks:
      - docker-networks
    environment:
      - REDIS_ADDRESS=redis:6379
      - KAFKA_ADDRESS=kafka:9092

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - docker-networks

  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - docker-networks
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=default

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - docker-networks
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    networks:
      - docker-networks
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


networks:
  docker-networks:
    name: docker-networks
    driver: bridge
    external: true
