app:
  version: 1.0
  name: core-engine
  host: 0.0.0.0                                 # Server IP
  port: 8080                                    # Server port
  ctxTimeout: 3m
grpc:
  host: 0.0.0.0
  port: 8081
security:
  jwt:
    key: admin
    duration: 2400h
dependencies:
  cache:
    address: localhost:6379
    password:
    database: 0
  messageBroker:
    brokers: localhost:9092
  database:
    read:
      host: localhost
      port: 5432
      user: root
      pass: root
      name: go-crypto-exchange
      debugLog: true # Please disable in Production Server
      pool:
        maxIdleConn: 5
        maxOpenConn: 100 
        maxConnLifeTime: 30s
        maxIdleLifeTime: 3s
    write:
      host: localhost
      port: 5432
      user: root
      pass: root
      name: go-crypto-exchange
      debugLog: true # Please disable in Production Server
      pool:
        maxIdleConn: 5
        maxOpenConn: 100 
        maxConnLifeTime: 30s
        maxIdleLifeTime: 3s