app:
  version: 1.0
  name: core-engine
  http:
    host: 0.0.0.0             # Server IP
    port: 8070                # Server port
    ctxTimeout: 3m
  grpc:
    host: 0.0.0.0
    port: 8081
  logging:
    logToTerminal: true       # Set log output to stdout
    logToFile: false           # Set log output to file
    location: /log/           # Location log file will be save in project directory
    fileLogName: server       # File log name.
    maxAge: 30                # Days before deleting log file.
    rotationFile: 24          # Hour before creating new file.
    hideSensitiveData: false  # Enable hide sensitive data with struct tag `log:"hide"`
security:
  jwt:
    key: admin
    duration: 2400h
dependencies:
  cache:
    address: localhost:6379
    password:
    database: 0
  messageBroker:
    brokers: localhost:9092
    group: core-engine
    consumer:
      topic:
        matchOrder: match-order
  database:
    read:
      host: localhost
      port: 5432
      user: root
      pass: admin
      name: go-crypto-exchange
      debugLog: false         # Disable for optimal performance
      pool:
        maxIdleConn: 25
        maxOpenConn: 40 
        maxConnLifeTime: 30m
        maxIdleLifeTime: 10s
    write:
      host: localhost
      port: 5432
      user: root
      pass: admin
      name: go-crypto-exchange
      debugLog: false         # Disable for optimal performance
      pool:
        maxIdleConn: 25
        maxOpenConn: 45
        maxConnLifeTime: 30m
        maxIdleLifeTime: 10s