app:
  version: 1.0
  name: matching-engine
  host: 0.0.0.0                                 # Server IP
  port: 8083                                    # Server port
  ctxTimeout: 3m
grpc:
  host: 0.0.0.0
  port: 8082
dependencies:
  cache:
    address: localhost:6379
    password:
    database: 0
  messageBroker:
    brokers: localhost:9092
    group: matching-engine
    consumer:
      topic: DOGEIDRT
    producer:
      topic: match-order
